# -*- coding: utf-8 -*-
"""heuristic functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fmQeYIRRCH2MKKuDHsM92HOcMbZDddXw
"""

heuristic = {
    'A': 10,
    'B': 6,
    'C': 3,
    'Goal': 0
}
print("Heuristic Values:")
for node in heuristic:
    print(node, ":", heuristic[node])
best = min(heuristic, key=heuristic.get)
print("\nBest Node to Visit:", best)

import heapq

# --- A* Search: f(n) = g(n) + h(n) ---
def a_star(graph, start, goal, h):
    pq = [(h[start], start, 0, [start])]
    seen = set()
    while pq:
        f, node, g, path = heapq.heappop(pq)
        if node == goal: return path, g
        if node in seen: continue
        seen.add(node)
        for nbr, cost in graph[node]:
            heapq.heappush(pq, (g+cost+h[nbr], nbr, g+cost, path+[nbr]))

# --- Greedy Best-First Search: f(n) = h(n) ---
def greedy_bfs(graph, start, goal, h):
    pq = [(h[start], start, [start])]
    seen = set()
    while pq:
        _, node, path = heapq.heappop(pq)
        if node == goal: return path
        if node in seen: continue
        seen.add(node)
        for nbr, _ in graph[node]:
            heapq.heappush(pq, (h[nbr], nbr, path+[nbr]))

# --- Hill Climbing: local search on an objective function ---
def hill_climb(f, x, step=1, iters=100):
    for _ in range(iters):
        left, right = f(x-step), f(x+step)
        if left > f(x) and left >= right: x -= step
        elif right > f(x): x += step
        else: break
    return x, f(x)


# --- Example graph & heuristic (straight-line distance to goal 'G') ---
graph = {
    'A': [('B', 1), ('C', 4)],
    'B': [('A', 1), ('D', 2), ('E', 5)],
    'C': [('A', 4), ('F', 3)],
    'D': [('B', 2), ('G', 6)],
    'E': [('B', 5), ('G', 2)],
    'F': [('C', 3), ('G', 1)],
    'G': []
}
heuristic = {'A': 7, 'B': 6, 'C': 4, 'D': 3, 'E': 1, 'F': 1, 'G': 0}

if __name__ == "__main__":
    print("A*:         ", a_star(graph, 'A', 'G', heuristic))
    print("Greedy BFS: ", greedy_bfs(graph, 'A', 'G', heuristic))
    print("Hill Climb: ", hill_climb(lambda x: -(x-3)**2 + 9, 0))